/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lnqjwxbvwxucltwufyef"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxucWp3eGJ2d3h1Y2x0d3VmeWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4ODYxMjIsImV4cCI6MjA4NTQ2MjEyMn0.WA93dAVat5Z2cgzx-duX1-cYPt44_j5lOGjokRoxF4A"